### ISSUE TITLE
Update function names with concept conventions

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/tbeptools#3]
Should follow the convention defined in the pkgdown site yaml 

```yaml
reference:
- title: "Read"
  contents:
  - starts_with("read_")
- title: "Analyze"
  contents:
  - starts_with("anlz_")
- title: "Visualize"
  contents:
  - starts_with("map_")
  - starts_with("show_")
```
